FROM scaleway-worker:authenticated-production

# Copy server.js
USER root
WORKDIR /scaleway/worker
COPY server.js .

# Install Express if not present
RUN cd /scaleway && npm install express

# Ensure ownership
RUN chown -R scaleway:scaleway /scaleway
USER scaleway

EXPOSE 8080
ENTRYPOINT ["node", "/scaleway/worker/server.js"]