services:
  worker:
    image: fondation/worker:authenticated
    container_name: fondation-worker
    restart: unless-stopped
    environment:
      - CONVEX_URL=${CONVEX_URL:-https://basic-stoat-666.convex.cloud}
      - CONVEX_DEPLOYMENT=${CONVEX_DEPLOYMENT:-dev:basic-stoat-666}
      - DOCKER_CONTAINER=true
      - NODE_ENV=production
      - WORKER_ID=docker-worker-001
      - POLL_INTERVAL=${POLL_INTERVAL:-5000}
      - LEASE_TIME=${LEASE_TIME:-300000}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL:-60000}
      - MAX_CONCURRENT_JOBS=${MAX_CONCURRENT_JOBS:-1}
      - TEMP_DIR=/tmp/fondation
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      # Use named volume for better persistence
      - worker-repos:/tmp/fondation
      # Optional: Mount Claude config from host
      # - ~/.config/claude:/root/.config/claude:ro
    ports:
      - "8081:8081"  # Health check endpoint
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  worker-repos:
    driver: local