version: '3.8'

services:
  # Fondation Worker Service
  worker:
    image: fondation/cli:latest
    container_name: fondation-worker
    restart: unless-stopped
    environment:
      # Required: Convex Database URL
      - CONVEX_URL=${CONVEX_URL}
      
      # Required: Authentication Tokens
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN}
      
      # Worker Configuration
      - WORKER_ID=${WORKER_ID:-worker-prod}
      - POLL_INTERVAL=${POLL_INTERVAL:-5000}
      - LEASE_TIME=${LEASE_TIME:-300000}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL:-60000}
      - MAX_CONCURRENT_JOBS=${MAX_CONCURRENT_JOBS:-1}
      
      # Docker Flag
      - DOCKER_CONTAINER=true
      
      # Temp Directory
      - TEMP_DIR=/tmp/fondation
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Network
    networks:
      - fondation-network
    
    # Volumes for persistent data
    volumes:
      - worker-temp:/tmp/fondation
      - worker-cache:/root/.cache
    
    command: worker

  # Optional: Multiple workers for scaling
  worker-2:
    extends:
      service: worker
    container_name: fondation-worker-2
    environment:
      # Inherit all from worker service
      - CONVEX_URL=${CONVEX_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN}
      - WORKER_ID=${WORKER_ID_2:-worker-prod-2}
      - POLL_INTERVAL=${POLL_INTERVAL:-5000}
      - LEASE_TIME=${LEASE_TIME:-300000}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL:-60000}
      - MAX_CONCURRENT_JOBS=${MAX_CONCURRENT_JOBS:-1}
      - DOCKER_CONTAINER=true
      - TEMP_DIR=/tmp/fondation
    profiles:
      - scale

# Networks
networks:
  fondation-network:
    driver: bridge

# Volumes
volumes:
  worker-temp:
    driver: local
  worker-cache:
    driver: local
