version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - CONVEX_URL=${CONVEX_URL}
      - WORKER_ID=docker-worker-1
      - POLL_INTERVAL=${POLL_INTERVAL:-5000}
      - LEASE_TIME=${LEASE_TIME:-300000}
      - HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL:-60000}
      - MAX_CONCURRENT_JOBS=${MAX_CONCURRENT_JOBS:-1}
      - TEMP_DIR=/tmp/fondation
    volumes:
      # Claude CLI credentials - mount for persistence
      # First run: docker-compose run worker /bin/sh -c "claude login"
      # Then: docker-compose up -d
      - claude-creds:/home/worker/.claude:ro
      - worker-tmp:/tmp/fondation
    ports:
      - "8080:8080"  # Health check endpoint
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  claude-creds:
    driver: local
  worker-tmp:
    driver: local