version: '3.8'

services:
  fondation-analyze:
    build:
      context: .
      dockerfile: Dockerfile
    image: fondation-analyze:latest
    container_name: fondation-analyze
    volumes:
      # Mount the codebase to analyze (read-only)
      - ${PROJECT_PATH:-./}:/workspace:ro
      # Mount output directory for results
      - ${OUTPUT_PATH:-./analysis-output}:/output
      # Optional: Mount Claude config directory if needed
      # - ~/.config/claude:/home/fondation/.config/claude:ro
    environment:
      # Claude API configuration
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-sonnet-4-20250514}
      - CLAUDE_OUTPUT_DIR=/output
      # Optional: Enable verbose logging
      - VERBOSE=${VERBOSE:-false}
    command: ["analyze", "/workspace", "--output-dir", "/output"]
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Alternative service for dry-run testing
  fondation-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: fondation-analyze:latest
    container_name: fondation-test
    volumes:
      - ${PROJECT_PATH:-./}:/workspace:ro
      - ${OUTPUT_PATH:-./test-output}:/output
    environment:
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-sonnet-4-20250514}
      - CLAUDE_OUTPUT_DIR=/output
    command: ["analyze", "/workspace", "--output-dir", "/output", "--dry-run", "--verbose"]